/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M3
 * Generated at: 2016-04-08 03:41:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.haisijia.common.AppRegistry;
import com.haisijia.model.JspParamsVo;
import com.haisijia.model.AppModel;
import com.haisijia.model.MenuVo;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.haisijia.model.AppModel");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.haisijia.model.JspParamsVo");
    _jspx_imports_classes.add("com.haisijia.model.MenuVo");
    _jspx_imports_classes.add("com.haisijia.common.AppRegistry");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

AppModel appModel = (AppModel)request.getAttribute("model");
JspParamsVo jspParamsVo = appModel.getJspParamsVo();
String title = jspParamsVo.getParamValue("title").orElse("");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>");
      out.print(title);
      out.write("</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t<!-- STYLESHEETS -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"js/flot/excanvas.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cloud-admin.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"css/themes/default.css\" id=\"skin-switcher\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"css/responsive.css\" >\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- JQUERY UI-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/jquery-ui-1.10.3.custom/css/custom-theme/jquery-ui-1.10.3.custom.min.css\" />\r\n");
      out.write("\t<!-- DATE RANGE PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/bootstrap-daterangepicker/daterangepicker-bs3.css\" />\r\n");
      out.write("\t<!-- BOOTSTRAP SWITCH -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/bootstrap-switch/bootstrap-switch.min.css\" />\r\n");
      out.write("\t<!-- HUBSPOT MESSENGER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-spinner.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-air.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-block.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-flat.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-future.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-ice.min.css\" />\r\n");
      out.write("\t<!-- MAGIC SUGGEST -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/magic-suggest/magicsuggest-1.3.1-min.css\" />\r\n");
      out.write("\t<!-- DATE PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.date.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.time.min.css\" />\r\n");
      out.write("\t<!-- COLOR PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/colorpicker/css/colorpicker.min.css\" />\r\n");
      out.write("\t<!-- FONTS -->\r\n");
      out.write("\t<!-- <link href='http://fonts.useso.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'> -->\r\n");
      out.write("    <link href='css/app_font.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<!-- JQUERY -->\r\n");
      out.write("\t<script src=\"js/jquery/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("\t<!-- JQUERY UI-->\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t<!-- BOOTSTRAP -->\r\n");
      out.write("\t<script src=\"bootstrap-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- 本工程工具 -->\r\n");
      out.write("\t<script src=\"js/app_util.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"bodyId\">\r\n");
      out.write("\t<!-- HEADER -->\r\n");
      out.write("\t<header class=\"navbar clearfix\" id=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t<!-- COMPANY LOGO -->\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/logo/logo.png\" alt=\"Cloud Admin Logo\" class=\"img-responsive\" height=\"30\" width=\"120\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<!-- /COMPANY LOGO -->\r\n");
      out.write("\t\t\t\t\t<!-- TEAM STATUS FOR MOBILE -->\r\n");
      out.write("\t\t\t\t\t<div class=\"visible-xs\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"team-status-toggle switcher btn dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-users\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /TEAM STATUS FOR MOBILE -->\r\n");
      out.write("\t\t\t\t\t<!-- SIDEBAR COLLAPSE -->\r\n");
      out.write("\t\t\t\t\t<div id=\"sidebar-collapse\" class=\"sidebar-collapse btn\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\" \r\n");
      out.write("\t\t\t\t\t\t\tdata-icon1=\"fa fa-bars\" \r\n");
      out.write("\t\t\t\t\t\t\tdata-icon2=\"fa fa-bars\" ></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /SIDEBAR COLLAPSE -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- NAVBAR LEFT -->\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav pull-left hidden-xs\" id=\"navbar-left\">\r\n");
      out.write("\t\t\t\t\t");

					List<MenuVo> topMenus = appModel.getTopMenus();
					String menuSelectedCss = "";
					for (MenuVo menu : topMenus) { 
						if (appModel.getSelectedTopMenuId() == menu.getMenuId()) {
							menuSelectedCss = "background-color: #8fb4d8;";
						} else {
							menuSelectedCss = "";
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\" style=\"");
      out.print(menuSelectedCss);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"mainMenu1\" href=\"");
      out.print(menu.getMenuUrl());
      out.write("&stmId=");
      out.print(menu.getMenuId());
      out.write("\" \r\n");
      out.write("                                                class=\"team-status-toggle dropdown-toggle tip-bottom\" data-toggle=\"tooltip\" title=\"");
      out.print(menu.getMenuName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-users\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"forum\" class=\"name\">");
      out.print(menu.getMenuName());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("\t\t\t\t<!-- /NAVBAR LEFT -->\r\n");
      out.write("\t\t\t\t<!-- BEGIN TOP NAVIGATION MENU -->\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t\t<!-- BEGIN NOTIFICATION DROPDOWN -->\t\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\" id=\"header-notification\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <span class=\"badge\">7</span> -->\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu notification\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><i class=\"fa fa-bell\"></i> 7 Notifications</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-success\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">5 users online. </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Just now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-primary\"><i class=\"fa fa-comment\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">Martin commented.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>19 mins</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-warning\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">DW1 server locked.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>32 mins</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\"><i class=\"fa fa-twitter\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">Twitter connected.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>55 mins</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-danger\"><i class=\"fa fa-heart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">Jane liked. </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2 hrs</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-warning\"><i class=\"fa fa-exclamation-triangle\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">Database overload.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>6 hrs</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">See all notifications <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END NOTIFICATION DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<!-- BEGIN INBOX DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\" id=\"header-message\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t<!-- <span class=\"badge\">3</span> -->\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu inbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><i class=\"fa fa-envelope-o\"></i> 3 Messages</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"compose pull-right tip-right\" title=\"Compose message\"><i class=\"fa fa-pencil-square-o\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/avatars/avatar2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"from\">Jane Doe</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDuis autem vel eum iriure dolor in hendrerit in vulputate velit esse mole ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Just Now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/avatars/avatar1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"from\">Vince Pelt</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDuis autem vel eum iriure dolor in hendrerit in vulputate velit esse mole ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>15 min ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/avatars/avatar8.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"from\">Debby Doe</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDuis autem vel eum iriure dolor in hendrerit in vulputate velit esse mole ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2 hours ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">See all messages <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END INBOX DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<!-- BEGIN TODO DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\" id=\"header-tasks\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-tasks\"></i>\r\n");
      out.write("\t\t\t\t\t\t<!-- <span class=\"badge\">3</span> -->\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu tasks\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><i class=\"fa fa-check\"></i> 6 tasks in progress</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">60%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">25%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 25%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">25% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">40%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">40% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">70%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"70\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 70%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">70% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">65%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 35%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">See all tasks <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- END TODO DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<!-- BEGIN USER LOGIN DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown user\" id=\"header-user\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"username\">");
      out.print(appModel.getUserName());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-user\"></i>我的主页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-cog\"></i>论坛</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-eye\"></i>账号设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"logoutBtn\"><a href=\"#\"><i class=\"fa fa-power-off\"></i>退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                    <script type=\"text/javascript\">\r\n");
      out.write("                    $(document).ready(function() {\r\n");
      out.write("                        $(\"#logoutBtn\").bind(\"click\", logoutUser);\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    function logoutUser() {\r\n");
      out.write("                        var reqUrl = \"ajax?cmd=logoutUserAjax&userId=");
      out.print(appModel.getUserId());
      out.write("\";\r\n");
      out.write("                        $.ajax({\r\n");
      out.write("                            url: reqUrl,\r\n");
      out.write("                            type: \"GET\",\r\n");
      out.write("                            //data: { jsonReq: JSON.stringify(g_pqov_json) },\r\n");
      out.write("                            dataType: \"json\",\r\n");
      out.write("                            success: onLogoutUserOk,\r\n");
      out.write("                            error: onLogoutUserError\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    function onLogoutUserOk(json) {\r\n");
      out.write("                        window.location.href = \"main?cmd=showHome\";\r\n");
      out.write("                    }\r\n");
      out.write("                    function onLogoutUserError(msg) {\r\n");
      out.write("                        alert(\"退出系统失败：\" + msg.responseText + \"！\");\r\n");
      out.write("                    }\r\n");
      out.write("                    </script>\r\n");
      out.write("\t\t\t\t\t<!-- END USER LOGIN DROPDOWN -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- END TOP NAVIGATION MENU -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- TEAM STATUS -->\r\n");
      out.write("\t\t<div class=\"container team-status\" id=\"team-status\">\r\n");
      out.write("\t\t  <div id=\"scrollbar\">\r\n");
      out.write("\t\t\t<div class=\"handle\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div id=\"teamslider\">\r\n");
      out.write("\t\t\t  <ul class=\"team-list\">\r\n");
      out.write("\t\t\t\t<li class=\"current\">\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar3.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tYou\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 35%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 20%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">6</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">3</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">1</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tMax Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 15%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 40%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 20%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">2</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">8</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">4</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tJane Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 65%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 15%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">10</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">3</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">4</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar4.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tEllie Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 5%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 48%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 27%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">1</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">6</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">2</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar5.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tLisa Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 21%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 20%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 40%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">4</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">5</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">9</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar6.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tKelly Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 45%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 21%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">6</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">3</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">1</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar7.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tJessy Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 7%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 30%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">1</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">6</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">2</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t  <a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t  <span class=\"image\">\r\n");
      out.write("\t\t\t\t\t  <img src=\"images/avatars/avatar8.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t  <span class=\"title\">\r\n");
      out.write("\t\t\t\t\tDebby Doe\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-success\" style=\"width: 70%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">35% Complete (success)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-warning\" style=\"width: 20%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">20% Complete (warning)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar progress-bar-danger\" style=\"width: 5%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">10% Complete (danger)</span>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-green\">13</span> completed\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-orange\">7</span> in-progress\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-adjust\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge badge-red\">1</span> pending\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pull-right fa fa-list-ul\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t<!-- /TEAM STATUS -->\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--/HEADER -->\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
