/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M3
 * Generated at: 2016-04-08 03:40:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.haisijia.model.JspParamsVo;
import com.haisijia.yhis.model.LoginModel;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.haisijia.yhis.model.LoginModel");
    _jspx_imports_classes.add("com.haisijia.model.JspParamsVo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

LoginModel loginModel = (LoginModel)request.getAttribute("model");
JspParamsVo jspParamsVo = loginModel.getJspParamsVo();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>云HIS---系统登录页面</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t<!-- STYLESHEETS --><!--[if lt IE 9]><script src=\"js/flot/excanvas.min.js\"></script><script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><script src=\"http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js\"></script><![endif]-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cloud-admin.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"css/themes/default.css\" id=\"skin-switcher\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"css/responsive.css\" >\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- JQUERY UI-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/jquery-ui-1.10.3.custom/css/custom-theme/jquery-ui-1.10.3.custom.min.css\" />\r\n");
      out.write("\t<!-- DATE RANGE PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/bootstrap-daterangepicker/daterangepicker-bs3.css\" />\r\n");
      out.write("\t<!-- BOOTSTRAP SWITCH -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/bootstrap-switch/bootstrap-switch.min.css\" />\r\n");
      out.write("\t<!-- HUBSPOT MESSENGER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-spinner.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-air.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-block.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-flat.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-future.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/hubspot-messenger/css/messenger-theme-ice.min.css\" />\r\n");
      out.write("\t<!-- MAGIC SUGGEST -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/magic-suggest/magicsuggest-1.3.1-min.css\" />\r\n");
      out.write("\t<!-- DATE PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.date.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/datepicker/themes/default.time.min.css\" />\r\n");
      out.write("\t<!-- COLOR PICKER -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/colorpicker/css/colorpicker.min.css\" />\r\n");
      out.write("\t<!-- FONTS -->\r\n");
      out.write("\t<!-- <link href='http://fonts.useso.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'> -->\r\n");
      out.write("    <link href='css/app_font.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<!-- JQUERY -->\r\n");
      out.write("\t<script src=\"js/jquery/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("\t<!-- JQUERY UI-->\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t<!-- BOOTSTRAP -->\r\n");
      out.write("\t<script src=\"bootstrap-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- 本工程工具 -->\r\n");
      out.write("\t<script src=\"js/app_util.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- PAGE -->\r\n");
      out.write("\t<section id=\"page\">\r\n");
      out.write("\t\t\t<!-- HEADER -->\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<!-- NAV-BAR -->\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.php\"><img src=\"images/logo/logo-alt.png\" height=\"40\" alt=\"logo name\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/NAV-BAR -->\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!--/HEADER -->\r\n");
      out.write("\t\t\t<!-- LOGIN -->\r\n");
      out.write("\t\t\t<section id=\"login\" class=\"visible\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-box-plain\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"bigintro\">登录</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-40\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginName\">邮件地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"loginName\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginPwd\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"loginPwd\" type=\"password\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"loingPwd\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("                                    <div class=\"checkbox\" style=\"margin-left: 0px; padding-left: 0px;\">\r\n");
      out.write("                                        <input id=\"rememberMe\" type=\"checkbox\" style=\"text-align: left; width: 30px; padding: 0px !important; margin: 0px;\">\r\n");
      out.write("                                        <label style=\"position: relative; top: -5px;\">记住我</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"loginBtn\" class=\"btn btn-danger\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- SOCIAL LOGIN -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-20\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>使用第三方社交平台账户登录</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-20\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"social-login center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-primary btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-danger btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /SOCIAL LOGIN -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-helpers\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"swapScreen('forgot');return false;\">忘记密码？</a> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t还没有测序吧账户？ <a href=\"#\" onclick=\"swapScreen('register');return false;\">马上注册！</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!--/LOGIN -->\r\n");
      out.write("\t\t\t<!-- REGISTER -->\r\n");
      out.write("\t\t\t<section id=\"register\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-box-plain\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"bigintro\">注册</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-40\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"userName\">姓名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-font\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"userName\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"nickName\">昵称</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"nickName\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginNameReg\">邮件</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"loginNameReg\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginPwdReg\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"loginPwdReg\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginPwdRegRepeat\">重复密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check-square-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" style=\"padding-top: 5px;\" id=\"loginPwdRegRepeat\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"loginPwdRegRepeat\">头像</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check-square-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" placeholder=\"产品图片\"  name=\"files\" id=\"uploadFile\" /> \r\n");
      out.write("                                    <span style=\"color: red;\">(如果不能弹出文件选择框请刷新一下网页)</span>\r\n");
      out.write("                                    <input type=\"hidden\" class=\"form-control\" style=\"padding-top: 5px;\" name=\"userImage\" id=\"userImage\" value=\"upload/avatar/female_100x100.jpg\" />\r\n");
      out.write("                                    <div id=\"showimg\"><img src=\"upload/avatar/female_100x100.jpg\" style=\"width: 100px; height: 100px;\" /></div>     \r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("                                  \r\n");
      out.write("                                  \r\n");
      out.write("                                  \r\n");
      out.write("                                    <div class=\"checkbox\" style=\"margin-left: 0px; padding-left: 0px;\">\r\n");
      out.write("                                        <input id=\"agreeBtn\" type=\"checkbox\" style=\"text-align: left; width: 30px; padding: 0px !important; margin: 0px;\">\r\n");
      out.write("                                        <label style=\"position: relative; top: -5px;\">我同意<a href=\"#\">服务使用条款</a> 和 <a href=\"#\">隐私政策</a></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  \r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-actions\">                                    \r\n");
      out.write("                                    <button type=\"submit\" id=\"registerBtn\" class=\"btn btn-success\">注册</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- SOCIAL REGISTER -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-20\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>或者使用第三方社交平台账户</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-20\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"social-login center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-primary btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-danger btn-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /SOCIAL REGISTER -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-helpers\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"swapScreen('login');return false;\">返回登录页面</a> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!--/REGISTER -->\r\n");
      out.write("\t\t\t<!-- FORGOT PASSWORD -->\r\n");
      out.write("\t\t\t<section id=\"forgot\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-box-plain\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"bigintro\">重置密码</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-40\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">输入你的邮件</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-info\">给我发送重置指导信息</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-helpers\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"swapScreen('login');return false;\">返回登录页面</a> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- FORGOT PASSWORD -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--/PAGE -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("﻿\r\n");
      out.write("                                                            \r\n");
      out.write("<script src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("\tvar bar = $('.bar');\r\n");
      out.write("\tvar percent = $('.percent');\r\n");
      out.write("\tvar showimg = $('#showimg');\r\n");
      out.write("\tvar progress = $(\".progress\");\r\n");
      out.write("\tvar files = $(\".files\");\r\n");
      out.write("\tvar btn = $(\".btn span\");\r\n");
      out.write("\t$(\"#uploadFile\").wrap(\"<form id='myupload' action='index.php?f=c_file_uploader&c=CFileUploader&m=uploadFile&fileType=18' method='post' enctype='multipart/form-data'></form>\");\r\n");
      out.write("    $(\"#uploadFile\").change(function(){\r\n");
      out.write("\t\t$(\"#myupload\").ajaxSubmit({\r\n");
      out.write("\t\t\tdataType:  'json',\r\n");
      out.write("\t\t\tbeforeSend: function() {\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\tuploadProgress: function(event, position, total, percentComplete) {\r\n");
      out.write("    \t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tvar img = data.files[0].url;\r\n");
      out.write("                $(\"#userImage\").val(img);\r\n");
      out.write("\t\t\t\tshowimg.html(\"<img src='\"+img+\"' style='width: 100px; height:100px;' />\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhr){\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*$(\".delimg\").live('click',function(){\r\n");
      out.write("\t\tvar pic = $(this).attr(\"rel\");\r\n");
      out.write("\t\t$.post(\"action.php?act=delimg\",{imagename:pic},function(msg){\r\n");
      out.write("\t\t\tif(msg==1){\r\n");
      out.write("\t\t\t\tfiles.html(\"删除成功.\");\r\n");
      out.write("\t\t\t\tshowimg.empty();\r\n");
      out.write("\t\t\t\tprogress.hide();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});*/\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- DATE RANGE PICKER -->\r\n");
      out.write("\t<script src=\"js/bootstrap-daterangepicker/moment.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/bootstrap-daterangepicker/daterangepicker.min.js\"></script>\r\n");
      out.write("\t<!-- SLIMSCROLL -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jQuery-slimScroll-1.3.0/jquery.slimscroll.min.js\">\r\n");
      out.write("    </script><script type=\"text/javascript\" src=\"js/jQuery-slimScroll-1.3.0/slimScrollHorizontal.min.js\"></script>\r\n");
      out.write("\t<!-- BLOCK UI -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jQuery-BlockUI/jquery.blockUI.min.js\"></script>\r\n");
      out.write("\t<!-- BOOTSTRAP SWITCH -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap-switch/bootstrap-switch.min.js\"></script>\r\n");
      out.write("\t<!-- BOOTBOX -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootbox/bootbox.min.js\"></script>\r\n");
      out.write("\t<!-- HUBSPOT MESSENGER -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/hubspot-messenger/js/messenger.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/hubspot-messenger/js/messenger-theme-flat.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/hubspot-messenger/js/messenger-theme-future.js\"></script>\r\n");
      out.write("\t<!-- MAGIC SUGGEST -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/magic-suggest/magicsuggest-1.3.1-min.js\"></script>\r\n");
      out.write("\t<!-- TIMEAGO -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/timeago/jquery.timeago.min.js\"></script>\r\n");
      out.write("\t<!-- DATE PICKER -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/datepicker/picker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/datepicker/picker.date.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/datepicker/picker.time.js\"></script>\r\n");
      out.write("\t<!-- COLOR PICKER -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/colorpicker/js/bootstrap-colorpicker.min.js\"></script>\r\n");
      out.write("\t<!-- RATY -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-raty/jquery.raty.min.js\"></script>\r\n");
      out.write("\t<!-- COOKIE -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jQuery-Cookie/jquery.cookie.min.js\"></script>\r\n");
      out.write("\t<!-- CUSTOM SCRIPT -->\r\n");
      out.write("\t<script src=\"js/script.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#registerBtn\").bind(\"click\", registerUser);     \r\n");
      out.write("        $(\"#loginBtn\").bind(\"click\", loginUser);\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function() {\t\r\n");
      out.write("\t\t\tApp.setPage(\"login\");  //Set current page\r\n");
      out.write("\t\t\tApp.init(); //Initialise plugins and elements\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction swapScreen(id) {\r\n");
      out.write("\t\t\tjQuery('.visible').removeClass('visible animated fadeInUp');\r\n");
      out.write("\t\t\tjQuery('#'+id).addClass('visible animated fadeInUp');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" value=\"");
      out.print(request.getAttribute("originUrl"));
      out.write("\" />  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var g_originUrl = \"");
      out.print(request.getAttribute("originUrl"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("function registerUser() {\r\n");
      out.write("    var userName = $(\"#userName\").val();\r\n");
      out.write("    var nickName = $(\"#nickName\").val();\r\n");
      out.write("    var loginName = $(\"#loginNameReg\").val();\r\n");
      out.write("    var loginPwdReg = $(\"#loginPwdReg\").val();\r\n");
      out.write("    var loginPwdRegRepeat = $(\"#loginPwdRegRepeat\").val();\r\n");
      out.write("    var userImage = $(\"#userImage\").val();\r\n");
      out.write("    if (loginPwdReg != loginPwdRegRepeat) {\r\n");
      out.write("        alert(\"两次输入的密码不一致，请重新输入！\");\r\n");
      out.write("        return ;\r\n");
      out.write("    }\r\n");
      out.write("    var reqUrl = \"index.php?f=c_user&c=CUser&m=registerUserAjax\";\r\n");
      out.write("    var json = new Object();\r\n");
      out.write("    json.userName = userName;\r\n");
      out.write("    json.nickName = nickName;\r\n");
      out.write("    json.loginName = loginName;\r\n");
      out.write("    json.loginPwd = loginPwdReg;\r\n");
      out.write("    json.userImage = userImage;\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: reqUrl,\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        data: {\r\n");
      out.write("            jsonReq: JSON.stringify(json)\r\n");
      out.write("        },\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: onRegisterUserOk,\r\n");
      out.write("        error: onRegisterUserError\r\n");
      out.write("    });\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("function onRegisterUserOk(json) {\r\n");
      out.write("    //alert(JSON.stringify(json));\r\n");
      out.write("    var rst = confirm(\"您是否希望我们记住您？（这样您在两周内就可以不用登录直接访问！）\");\r\n");
      out.write("    var rememberMode = 0;\r\n");
      out.write("    if (rst) {\r\n");
      out.write("        rememberMode = 1;\r\n");
      out.write("    }\r\n");
      out.write("    setCookieAjax(json.userId, rememberMode);\r\n");
      out.write("}\r\n");
      out.write("function onRegisterUserError(msg) {\r\n");
      out.write("    alert(\"注册用户失败：\" + msg.responseText + \"！\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function setCookieAjax(userId, rememberMode) {\r\n");
      out.write("    var reqUrl = \"ajax?cmd=setCookieAjax&userId=\" + userId + \"&rememberMode=\" + rememberMode;\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: reqUrl,\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: onSetCookieAjaxOk,\r\n");
      out.write("        error: onSetCookieAjaxError\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function onSetCookieAjaxOk(json) {\r\n");
      out.write("    window.location.href = g_originUrl;\r\n");
      out.write("}\r\n");
      out.write("function onSetCookieAjaxError(msg) {\r\n");
      out.write("    alert(\"设置Cookie失败：\" + msg.responseText + \"！\");\r\n");
      out.write("    window.location.href = g_originUrl;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loginUser() {\r\n");
      out.write("    var loginName = $(\"#loginName\").val();\r\n");
      out.write("    var loginPwd = $(\"#loginPwd\").val();\r\n");
      out.write("    if (\"\" == loginName || \"\" == loginPwd) {\r\n");
      out.write("        alert(\"登录名、密码不能为空，请重新输入！\");\r\n");
      out.write("        return ;\r\n");
      out.write("    }\r\n");
      out.write("    var reqUrl = \"ajax?cmd=loginUserAjax&loginName=\" + loginName + \"&loginPwd=\" + loginPwd;\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: reqUrl,\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: onLoginUserAjaxOk,\r\n");
      out.write("        error: onLoginUserAjaxError\r\n");
      out.write("    });\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("function onLoginUserAjaxOk(json) {\r\n");
      out.write("    var userId = json.userId;\r\n");
      out.write("    var rememberMe = 0;\r\n");
      out.write("    if ($(\"#rememberMe\").prop(\"checked\")) {\r\n");
      out.write("        rememberMe = 1;\r\n");
      out.write("    }\r\n");
      out.write("    if (userId <= 0) {\r\n");
      out.write("        alert(\"我们无法找到您提供的用户名密码所对应的用户，请联系系统管理员！\");\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    setCookieAjax(userId, rememberMe);\r\n");
      out.write("}\r\n");
      out.write("function onLoginUserAjaxError(msg) {\r\n");
      out.write("    alert(\"登录失败：\" + msg.responseText + \"！\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t<!-- /JAVASCRIPTS -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
